#### 1. Import NumPy

Make sure to follow the conventions!

In [3]:
# Your code here
import numpy as np

#### 2. Create an array of 10 zeros 

In [4]:
# Your code here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# Expected output

#### 3. Create an array of 10 ones

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
# Expected output

#### 4. Create an array of 10 fives

In [8]:
np.full(10, 5.0)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
# Expected output

#### 5. Create a vector, named `arr`, of 10 zeros the fifth value of which is 1.

In [10]:
list = np.zeros(10)
list[4] = 1.0
list

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
# Expected output

#### 6. Create an array of the integers from 10 to 50

In [12]:
np.array(range(10, 50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
# Expected output

#### 7. Reverse an array in **TWO** ways: using 'the Python way' and using a NumPy function

In [14]:
arr = np.array([1, 2, 3])

arr2 = arr.tolist()
#Not sure if this is the exact python way
print(f"Using Python way {sorted(arr2, reverse=True)}")
print(f"Using a NumPy function: {arr[::-1]}")


# Your code here

Using Python way [3, 2, 1]
Using a NumPy function: [3 2 1]


In [15]:
# Expected output

#### 8. Create a 5x5 array with 1 on the border and 0 inside

In [16]:
np_arr = np.zeros((5,5))
np_arr[0] = 1
np_arr[4] = 1
np_arr[:,0] = 1
np_arr[:,4] = 1
np_arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# Expected output

#### 9. Add a border filled with 0's on the two sides of an array.

> Hint: [np.pad](https://numpy.org/doc/stable/reference/generated/numpy.pad.html)

In [18]:
np.pad(np.array([1, 2, 3]), (1,1), 'constant', constant_values=(0, 0))


array([0, 1, 2, 3, 0])

In [19]:
# Expected output

#### 10. Create an array of all the even integers from 10 to 50

In [20]:
np.array(np.arange(10, 51, 2))


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [21]:
# Expected output

#### 11. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
np.array(np.arange(9)).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
# Expected output

#### 12. Create a 3x3 identity matrix

In [24]:
arr = np.array(np.zeros(9)).reshape(3,3)
np.fill_diagonal(arr, 1)

arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# Expected output

#### 13. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

> Hint: [np.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

In [26]:
arr = np.array([1,2,3,4])
np.diag(arr , k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [27]:
# Expected output

#### 14. Use NumPy to generate a random number between 0 and 1

**Note**: Your result's value should be different from the one shown below.

In [28]:
np.random.rand(1)

array([0.61683299])

In [29]:
# Expected output

#### 15. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

**Note**: Your result's values should be different from the ones shown below.

In [30]:
np.random.normal(0,1, size=(25))
#from documentation

array([-5.01196064e-01, -1.38406855e+00,  6.78427768e-01, -7.85396266e-01,
        1.16641353e+00, -4.59638336e-01, -3.62743905e-01, -6.09013307e-01,
       -9.86026882e-01, -1.37035919e+00, -1.30407497e-01, -9.01755579e-02,
       -3.68406042e-01,  7.63651823e-01, -1.00257880e-03,  1.28900245e-01,
       -3.32365119e-01,  1.80568085e-01,  7.80681084e-01,  1.69491867e-01,
        1.26721297e+00,  7.45814413e-01,  4.88662270e-01, -1.13596617e+00,
        1.45710475e+00])

In [31]:
# Expected output

#### 16. Create a 3x3x3 array with random values drawn from the uniform distribution

**Note**: Your result's values should be different from the ones shown below.


In [32]:
np.random.uniform(size=(3,3,3))

array([[[0.57441165, 0.34602269, 0.43498372],
        [0.69582075, 0.79220492, 0.81080891],
        [0.74189553, 0.72231595, 0.72299635]],

       [[0.55363156, 0.25819808, 0.64282833],
        [0.11691367, 0.17141725, 0.26792875],
        [0.03870937, 0.50319908, 0.46309368]],

       [[0.147046  , 0.54861091, 0.64741959],
        [0.25198539, 0.76518594, 0.45402353],
        [0.82026967, 0.9034271 , 0.5054827 ]]])

In [33]:
# Expected output

#### 17. Create a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values.

**Note**: Your result's values should be different from the ones shown below.

In [34]:
arr = np.random.uniform(size=(10,10))
print(f"The array: {arr}")
print(f"It's min value: {arr.min()}")
print(f"It's max value: {arr.max()}")

The array: [[8.83712909e-01 8.96486820e-02 4.51298878e-01 1.37869878e-01
  5.75575962e-01 5.38400325e-01 4.29118915e-01 1.83279784e-01
  1.06515881e-01 7.12401746e-01]
 [6.29206446e-01 3.18943141e-01 5.98932044e-01 8.34928142e-01
  1.69177180e-01 4.12095289e-01 6.57077599e-01 4.40531076e-02
  1.04219603e-01 5.28867948e-01]
 [3.68791422e-01 8.33603141e-01 2.45724947e-01 7.44821859e-01
  7.91967979e-01 2.80681430e-01 7.18752884e-02 6.07484378e-01
  5.02340577e-01 5.05587036e-01]
 [5.18068758e-01 6.35701332e-01 3.35760653e-01 7.23832011e-01
  9.30576956e-01 5.75756013e-04 4.94763518e-01 4.18489132e-01
  9.36337688e-01 9.64406869e-01]
 [9.03564862e-01 2.30126904e-02 4.32521993e-01 9.17608396e-01
  3.86989950e-01 4.64110423e-01 4.60002071e-01 3.73412263e-01
  8.04168592e-02 2.75238212e-01]
 [5.33290625e-01 5.82349329e-01 5.79554422e-01 9.10102652e-01
  1.26425280e-01 3.93602251e-02 6.68401186e-01 2.29597361e-01
  8.16979096e-02 7.21425292e-01]
 [1.61764758e-03 1.59566418e-01 7.38661286e-01 

In [35]:
# Expected output

#### 18. Create a random array with values drawn from the uniform distribution of size 30 and find the mean value

In [36]:
arr = np.random.uniform(size=(30))
print(f"The array: {arr}")
print(f"Its mean: {arr.mean()}")

The array: [0.27620374 0.27567555 0.57294163 0.01404347 0.09327468 0.12144025
 0.88271385 0.37203271 0.26189591 0.81657736 0.88390195 0.64984442
 0.16166434 0.75385389 0.53109046 0.24889883 0.52707948 0.02457492
 0.77134551 0.65115658 0.09370535 0.45486488 0.09943266 0.02045374
 0.35583994 0.90433453 0.53684271 0.03656719 0.62699024 0.48523663]
Its mean: 0.41681591368205123


In [37]:
# Expected output

#### 19. Create the following matrix:

In [38]:
arr = np.arange(1, 101).reshape(10,10)
arr / 100


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [39]:
# Expected output

#### 20. Create an array of 20 linearly spaced points between 0 and 1:

In [40]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [41]:
# Expected output

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs.

In all of the solutions until the last task before the section `NumPy Operations` you should be using `mat`.

In [42]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 21. Write code that reproduces the output shown below.

In [43]:
# CODE HERE
mat = np.arange(1,26).reshape(5,5)
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [44]:
# Expected output

#### 22. Write code that reproduces the output shown below.

In [45]:
mat = np.arange(1,26).reshape(5,5)
mat[3,4]

np.int64(20)

In [46]:
# Expected output

#### 23. Write code that reproduces the output shown below.

In [47]:
mat = np.arange(1,26).reshape(5,5)
#mat
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [48]:
# Expected output

#### 24. Write code that reproduces the output shown below.

In [49]:
mat = np.arange(1,26).reshape(5,5)
#mat
mat[4]

array([21, 22, 23, 24, 25])

In [50]:
# Expected output

#### 25. Write code that reproduces the output shown below.

In [51]:
mat = np.arange(1,26).reshape(5,5)
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
# Expected output

#### 26. Find the indices of the non-zero elements in the provided array.

In [72]:
arr = np.array([1,2,0,0,4,0])
#np.where(arr != 0, arr, np.indices(arr))
l = list(np.where(arr != 0))
print(l)
# Your code here

TypeError: 'numpy.ndarray' object is not callable

In [54]:
# Expected output

## NumPy Operations

#### 27. Get the sum of all the values in mat

In [55]:
mat = np.arange(1,26).reshape(5,5)
mat
mat.sum()

np.int64(325)

In [56]:
# Expected output

#### 28. Get the standard deviation of the values in mat

In [73]:
mat = np.arange(1,26).reshape(5,5)
mat.std()

np.float64(7.211102550927978)

In [58]:
# Expected output

#### 29. Get the sum of all the columns in mat

In [59]:
mat = np.arange(1,26).reshape(5,5)
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [60]:
# Expected output

#### 30. Create and multiply a 5x3 matrix by a 3x2 matrix (matrix product). The matrices can hold random values or you can create them manually.

**Note**: In this example output the matrices held random values, so your result's values should be different from the ones shown below.

In [61]:
mat1 = np.arange(1,16).reshape(5,3)
mat1

mat2 = np.arange(1,7).reshape(3,2)
mat2

np.matmul(np.arange(1,16).reshape(5,3), np.arange(1,7).reshape(3,2))
#i can use @ also here


array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

In [62]:
# Expected output

#### 31. Create a 1D array of random integers between 0 and 9. Negate all elements which are between 3 and 8.

In [63]:
nums = np.random.randint(0,10, 10)
nums = np.where((nums >= 3) & (nums <= 8), -nums, nums)
nums

array([ 0,  1, -7, -3,  2,  2,  0,  9, -8, -3], dtype=int32)

In [64]:
# Expected output

#### 32. Create a random array of size 10 and sort it

In [65]:
mat = np.sort(np.random.random(10))
mat

array([0.21918379, 0.3585118 , 0.45231483, 0.46751021, 0.46970618,
       0.52201825, 0.53325344, 0.66577266, 0.75420476, 0.86949233])

In [66]:
# Expected output

#### 33. Create random vector of values drawn from the uniform distribution of size 10 and replace the maximum value by 0

In [67]:
mat = np.random.uniform(0,1, 10)
print(f"The array: {mat}")
mat = np.sort(mat)
mat[-1] = 0
print(f"The result {mat}")

The array: [0.36771056 0.55021642 0.74065637 0.52836981 0.76633304 0.95766905
 0.19410103 0.27717362 0.65142695 0.74768968]
The result [0.19410103 0.27717362 0.36771056 0.52836981 0.55021642 0.65142695
 0.74065637 0.74768968 0.76633304 0.        ]


In [68]:
# Expected output

#### 34. What function can we use to ensure that we always get the same random numbers?

> **Your answer**: seed?